version: '3.8'

services:
  app:
    build: .
    container_name: php-lms-app-staging
    ports:
      - "8080:80"
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/sessions:/var/www/html/storage/sessions
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - db
    env_file:
      - .env.staging
    restart: unless-stopped
    networks:
      - lms-network

  db:
    image: mysql:8.0
    container_name: php-lms-db-staging
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_staging_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    networks:
      - lms-network

volumes:
  db_staging_data:

networks:
  lms-network:
    driver: bridge